title: Mary's New Page
description: Trying to use just-the-docs/Github pages/Jekyll for the first time
theme: just-the-docs

url: https://kiddmary.github.io/just-the-docs

aux_links:
  Template Repository: https://kiddmary.github.io/just-the-docs
